# Generated by Django 4.0.4 on 2024-03-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildcardtype',
            name='show_in_form',
        ),
        migrations.RemoveField(
            model_name='vappcardtype',
            name='show_in_form',
        ),
    ]
