# Generated by Django 4.0.4 on 2024-04-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_buildregistrations_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildregistrations',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='buildregistrations',
            name='mobile',
            field=models.TextField(null=True),
        ),
    ]
