# Generated by Django 4.0.4 on 2024-04-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_buildregistrations_dob_buildregistrations_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildregistrations',
            name='lanyard_color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
