# Generated by Django 4.0.4 on 2024-05-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_buildregistrations_lanyard_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='daysTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'event_daystable',
            },
        ),
        migrations.AddField(
            model_name='eventregistrations',
            name='days',
            field=models.ManyToManyField(to='portal.daystable'),
        ),
    ]
