# Generated by Django 4.0.4 on 2024-05-14 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('portal', '0008_userrole'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userrole',
            table='user_profile_role',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.userrole')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
