# Generated by Django 4.0.4 on 2024-05-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_rename_userprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='daystable',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
