# Generated by Django 4.0.4 on 2024-05-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_daystable_entries'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='daystable',
            table='event_days',
        ),
    ]
