# Generated by Django 4.0.4 on 2024-05-15 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_in_and_check_out', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='activate',
            new_name='active',
        ),
    ]
