# Generated by Django 4.0.4 on 2024-05-15 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check_in_and_check_out', '0002_rename_activate_rooms_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrylog',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='check_in_and_check_out.rooms'),
            preserve_default=False,
        ),
    ]
