# Generated by Django 4.0.4 on 2024-05-20 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_daystable_date'),
        ('check_in_and_check_out', '0003_entrylog_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrylog',
            name='day',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.daystable'),
        ),
    ]
