# Generated by Django 4.0.4 on 2024-05-20 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_daystable_date'),
        ('check_in_and_check_out', '0004_entrylog_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrylog',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day', to='portal.daystable'),
        ),
    ]
