# Generated by Django 4.0.4 on 2024-05-20 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_in_and_check_out', '0005_alter_entrylog_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrylog',
            name='day',
        ),
    ]
